---
# tasks file for sysdev.openshift

- name: download and untar openshift
  unarchive:
    #src: "https://github.com/openshift/origin/releases/download/v3.9.0/openshift-origin-server-v3.9.0-191fece-linux-64bit.tar.gz"
    src: "https://github.com/openshift/origin/releases/download/v3.10.0/openshift-origin-server-v3.10.0-dd10d17-linux-64bit.tar.gz"
    copy: no
    dest: "/tmp"
- name: move openshift files to usr/local/sbin
  shell: mv o* k* h* t* /usr/local/sbin
  args:
    chdir: /tmp/openshift-origin-server-v3.10.0-dd10d17-linux-64bit.tar.gz
- name: get public ip address
  shell: curl ipecho.net/plain
  register:  ip_pub 
- name: copy and paste this message 
  debug: 
    msg: "/usr/local/sbin/oc cluster up --public-hostname={{ ip_pub }} --host-data-dir=/home/centos/opens_data "

