---
# tasks for sysdev.docker
- name: Install require packages
  become: true
  dnf: name={{item}} state=present 
  with_items:
    - git
    - wget
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
- name: Add docker repo
  command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  changed_when: false
- name: Add ce edge
  command:  dnf config-manager --set-enable docker-ce-edge
  changed_when: false
- name: Add ce test
  command:  dnf  config-manager --set-enable docker-ce-test
  changed_when: false
- name: Add docker package for Openshift
  dnf: name=docker-ce-17.09.1.ce-1.el7.centos state=present 
- name: Change docker.service
  lineinfile: dest=/usr/lib/systemd/system/docker.service
     state=present
     regexp='ExecStart=/usr/bin/dockerd'
     line='ExecStart=/usr/bin/dockerd --insecure-registry 172.30.0.0/16'
     backup=yes
- name: service docker start
  service: name=docker state=started enabled=yes
- name:  install monitoring
  dnf: name={{item}} state=present 
  with_items:
    - htop
    - iotop
    - iftop
- name: install python pip
  dnf: name=python-pip state=present 
- name: Install docker-compose and others
  pip:  name={{item}}
  with_items:
    - docker-compose
    - pyopenssl
    - ndg-httpsclient
    - pyasn1
